### ISSUE TITLE
meta data 

### ISSUE THREAD

**Issue by seanysean** [seanysean/EZ-CSS#42]
- [ ] The chesswithsean web page
- [ ] The main page of this repo
- [ ] Doc templates
- [ ] Ec colors page
- [ ] Ec cards page
